CREATE TABLE ROLES (
    ID BIGSERIAL PRIMARY KEY,
    ROLE VARCHAR(100)
);

INSERT INTO
    ROLES (ROLE)
VALUES
    ('Admin'),
    ('User');

CREATE TABLE PROVINCES (
    ID BIGSERIAL PRIMARY KEY,
    REGION VARCHAR(100),
    PROVINCE VARCHAR(100)
);

CREATE TABLE COMPANY_TYPES (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(100) UNIQUE,
    SUBSCRIPTION_COST NUMERIC(10, 2),
    APPROVAL BOOLEAN DEFAULT FALSE
);

INSERT INTO
    COMPANY_TYPES (TYPE, SUBSCRIPTION_COST)
VALUES
    ('SME', 300),
    ('Bank', 3000),
    ('Government Officers', 3000),
    ('Development Partners', 10000),
    ('Private Companies', 5000);

CREATE TABLE COMPANIES (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(200),
    PROVINCE_ID BIGINT REFERENCES PROVINCES(ID),
    TYPE_ID BIGINT REFERENCES COMPANY_TYPES(ID),
    CREATED_TIME BIGINT,
    HAS_BILLBOARDS BOOLEAN DEFAULT FALSE,
    HAS_DETAILS BOOLEAN DEFAULT FALSE
);

CREATE TABLE BILLBOARD_STATUSES (
    ID SERIAL PRIMARY KEY,
    STATUS VARCHAR(50) UNIQUE
);

INSERT INTO
    BILLBOARD_STATUSES (STATUS)
VALUES
    ('Pending'),
    ('Approved'),
    ('Rejected');

CREATE TABLE BILLBOARDS (
    ID BIGSERIAL PRIMARY KEY,
    IMAGE VARCHAR(100),
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    INDEX INT,
    ACTIVE BOOLEAN DEFAULT FALSE
);

CREATE TABLE BILLBOARD_REQUESTS (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    STATUS_ID INT REFERENCES BILLBOARD_STATUSES(ID),
    REMARK VARCHAR(250),
    CREATED_TIME BIGINT,
    MODIFIED_TIME BIGINT,
    MODIFIED_BY BIGINT REFERENCES USERS(ID)
);

CREATE TABLE BILLBOARD_REQUEST_BILLBOARDS (
    BILLBOARD_ID BIGINT REFERENCES BILLBOARDS(ID),
    REQUEST_ID BIGINT REFERENCES BILLBOARD_REQUESTS(ID),
    PRIMARY KEY(BILLBOARD_ID, REQUEST_ID)
);

CREATE TABLE SMES (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    YEAR INT,
    EMP_MALE INT,
    EMP_FEMALE INT,
    LATITUDE NUMERIC(10, 2),
    LONGITUDE NUMERIC(10, 2),
    DESCRIPTION TEXT,
    FINANCE_ADVICE BOOLEAN,
    GREEN_FINANCE BOOLEAN,
    SMM BOOLEAN,
    WOMEN_LED BOOLEAN,
    FACEBOOK VARCHAR(200),
    INSTAGRAM VARCHAR(200),
    TWITTER VARCHAR(200),
    WHATSAPP VARCHAR(200),
    SNAPCHAT VARCHAR(200),
    ADDRESS_1 VARCHAR(200),
    ADDRESS_2 VARCHAR(200),
    WEBSITE VARCHAR(150),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(100)
);

CREATE TABLE PRIVATE_COMPANIES (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    YEAR INT,
    EMP_MALE INT,
    EMP_FEMALE INT,
    LATITUDE NUMERIC(10, 2),
    LONGITUDE NUMERIC(10, 2),
    DESCRIPTION TEXT,
    FINANCE_ADVICE BOOLEAN,
    GREEN_FINANCE BOOLEAN,
    SMM BOOLEAN,
    FACEBOOK VARCHAR(200),
    INSTAGRAM VARCHAR(200),
    TWITTER VARCHAR(200),
    WHATSAPP VARCHAR(200),
    SNAPCHAT VARCHAR(200),
    ADDRESS_1 VARCHAR(200),
    ADDRESS_2 VARCHAR(200),
    WEBSITE VARCHAR(150),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(50)
);

CREATE TABLE BANKS (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    YEAR INT,
    EMP_MALE INT,
    EMP_FEMALE INT,
    LATITUDE NUMERIC(10, 2),
    LONGITUDE NUMERIC(10, 2),
    SMM BOOLEAN,
    CLIMATE_FINANCE BOOLEAN,
    FACEBOOK VARCHAR(200),
    INSTAGRAM VARCHAR(200),
    TWITTER VARCHAR(200),
    WHATSAPP VARCHAR(200),
    SNAPCHAT VARCHAR(200),
    ADDRESS_1 VARCHAR(200),
    ADDRESS_2 VARCHAR(200),
    WEBSITE VARCHAR(150),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(50)
);

CREATE TABLE GOVERNMENT_DEPARTMENTS (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    YEAR INT,
    EMP_MALE INT,
    EMP_FEMALE INT,
    LATITUDE NUMERIC(10, 2),
    LONGITUDE NUMERIC(10, 2),
    POPULATION INT,
    FACEBOOK VARCHAR(200),
    INSTAGRAM VARCHAR(200),
    TWITTER VARCHAR(200),
    WHATSAPP VARCHAR(200),
    SNAPCHAT VARCHAR(200),
    ADDRESS_1 VARCHAR(200),
    ADDRESS_2 VARCHAR(200),
    WEBSITE VARCHAR(150),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(50),
    CLIMATE_FINANCE BOOLEAN
);

CREATE TABLE DEVELOPMENT_PARTNERS (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    LATITUDE NUMERIC(10, 2),
    LONGITUDE NUMERIC(10, 2),
    PROJECTS INT,
    FACEBOOK VARCHAR(200),
    INSTAGRAM VARCHAR(200),
    TWITTER VARCHAR(200),
    WHATSAPP VARCHAR(200),
    SNAPCHAT VARCHAR(200),
    ADDRESS_1 VARCHAR(200),
    ADDRESS_2 VARCHAR(200),
    WEBSITE VARCHAR(150),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(50)
);

CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(200),
    PHONE VARCHAR(10),
    EMAIL VARCHAR(100) UNIQUE,
    ROLE_ID BIGINT REFERENCES ROLES(ID),
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    PASSWORD VARCHAR(500)
);

INSERT INTO
    USERS (NAME, EMAIL, ROLE_ID, PASSWORD)
VALUES
    (
        'E Hauswin Admin',
        'admin@e-hauswin.com',
        1,
        'EHausWin@32!'
    );

-- iframe link: https://maps.google.com/maps?q=<LATITUDE>,<LONGITUDE>&z=14&output=embed
-- iframe link: https://maps.google.com/maps?q=12.9164446,80.086309&z=14&output=embed
CREATE TABLE SUBSCRIPTIONS (
    ID BIGSERIAL PRIMARY KEY,
    COMPANY_ID BIGINT REFERENCES COMPANIES(ID),
    START_DATE BIGINT,
    END_DATE BIGINT,
    TIME BIGINT,
    DESCRIPTION VARCHAR(250),
    METHOD VARCHAR(25),
    AMOUNT NUMERIC(10, 2),
    PAYMENT_DATE BIGINT,
    REFERENCE_NO VARCHAR(100),
    BANK VARCHAR(100),
    BRANCH VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS OAUTHS (
    ID BIGSERIAL PRIMARY KEY,
    PROVIDER VARCHAR(25),
    ACCESS_TOKEN VARCHAR(100),
    REFRESH_TOKEN VARCHAR(100),
    EXPIRY BIGINT
);

INSERT INTO
    OAUTHS (PROVIDER)
VALUES
    ('zoho');

CREATE TABLE RESET_PASSWORDS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES USERS(ID),
    CODE VARCHAR(250),
    TIME BIGINT
);