import {
    IconBuilding,
    IconBuildingArch,
    IconBuildingBank,
    IconBuildingBridge,
    IconBuildingCommunity,
    IconBuildingFactory,
    IconDashboard,
    IconEdit,
    IconFrame,
    IconList,
    IconMoneybag,
    IconPigMoney,
    IconReportMoney,
    IconUser,
    IconZoomMoney
} from "@tabler/icons-react";

const menuItems = {
    items: [
        {
            id: 'dashboard',
            title: 'Dashboard',
            type: 'group',
            children: [
                {
                    id: 'admin-dashboard',
                    title: 'Dashboard',
                    type: 'item',
                    url: '/admin',
                    icon: IconDashboard,
                    roles: ['Admin'],
                },
                {
                    id: 'admin-users',
                    title: 'All Users',
                    type: 'item',
                    url: '/admin/users',
                    icon: IconUser,
                    roles: ['Admin'],
                },
                {
                    id: 'subscription-cost',
                    title: 'Subscription Cost',
                    type: 'item',
                    url: '/admin/subscription-cost',
                    icon: IconPigMoney,
                    roles: ['Admin'],
                },
                {
                    id: 'user-dashboard',
                    title: 'Dashboard',
                    type: 'item',
                    url: '/dashboard',
                    icon: IconDashboard,
                    roles: ['User'],
                },
                {
                    id: 'user-subscription',
                    title: 'My Subscriptions',
                    type: "item",
                    url: "/dashboard/subscriptions",
                    icon: IconReportMoney,
                    roles: ['User'],
                },
                {
                    id: 'edit-details',
                    title: "Edit Details",
                    type: "item",
                    url: "/dashboard/details",
                    icon: IconEdit,
                    roles: ['User'],
                },
                {
                    id: 'admin-billboards',
                    title: "Billboard Requests",
                    type: "collapse",
                    icon: IconFrame,
                    roles: ['Admin'],
                    children: [
                        {
                            id: 'all-billboard-requests',
                            title: "All Requests",
                            type: "item",
                            url: "/admin/billboards",
                            roles: ['Admin'],
                        },
                        {
                            id: 'pending-billboard-requests',
                            title: "Pending",
                            type: "item",
                            url: "/admin/billboards/pending",
                            roles: ['Admin'],
                        },
                        {
                            id: 'approved-billboard-requests',
                            title: "Approved",
                            type: "item",
                            url: "/admin/billboards/approved",
                            roles: ['Admin'],
                        },
                        {
                            id: 'rejected-billboard-requests',
                            title: "Rejected",
                            type: "item",
                            url: "/admin/billboards/rejected",
                            roles: ['Admin'],
                        },
                    ]
                },
            ],
        },
        {
            id: 'billboards',
            title: 'Billboard',
            type: 'group',
            roles: ['User'],
            children: [
                {
                    id: 'view-billboards',
                    title: "Bill Boards",
                    type: "item",
                    url: "/dashboard/billboards",
                    icon: IconFrame,
                    roles: ['User'],
                },
                {
                    id: 'billboards-requests',
                    title: "Bill Board Requests",
                    type: "item",
                    url: "/dashboard/billboard/requests",
                    icon: IconList,
                    roles: ['User'],
                },
            ],
        },
        {
            id: 'companies',
            title: "Companies",
            type: "group",
            roles: ['Admin'],
            children: [
                {
                    id: "all-company-list",
                    title: "All Companies",
                    type: "item",
                    url: "/admin/companies",
                    icon: IconBuilding,
                },
                {
                    id: "sme",
                    title: "SME",
                    type: "item",
                    url: "/admin/companies/sme",
                    icon: IconBuildingArch,
                },
                {
                    id: "bank",
                    title: "Bank",
                    type: "item",
                    url: "/admin/companies/bank",
                    icon: IconBuildingBank,
                },
                {
                    id: "government",
                    title: "Government",
                    type: "item",
                    url: "/admin/companies/government",
                    icon: IconBuildingCommunity,
                },
                {
                    id: "development-partner",
                    title: "Development Partner",
                    type: "item",
                    url: "/admin/companies/development-partner",
                    icon: IconBuildingBridge,
                },
                {
                    id: "private-company",
                    title: "Private Companies",
                    type: "item",
                    url: "/admin/companies/private-company",
                    icon: IconBuildingFactory,
                },
            ],
        },
        {
            id: 'subscriptions',
            title: "Subscription",
            type: "group",
            roles: ['Admin'],
            children: [
                {
                    id: 'all-subscriptions',
                    title: "All Subscriptions",
                    type: "item",
                    url: "/admin/subscriptions",
                    icon: IconMoneybag,
                    roles: ['Admin'],
                },
                {
                    id: 'active-subscriptions',
                    title: "Active Subscriptions",
                    type: "item",
                    url: "/admin/subscriptions/active",
                    icon: IconReportMoney,
                    roles: ['Admin'],
                },
                {
                    id: 'inactive-subscriptions',
                    title: "Inactive Subscriptions",
                    type: "item",
                    url: "/admin/subscriptions/inactive",
                    icon: IconZoomMoney,
                    roles: ['Admin'],
                },
            ],
        },
    ]
};

export default menuItems;
